//! Wire-compatibility skeleton for the reimplemented `meshtastic` protobuf
//! schema (`proto/*.proto`).
//!
//! WHY this file is separate from the self-roundtrip tests in `lib.rs`:
//! encoding a message with THIS crate's own `prost`-generated code and then
//! decoding it with the SAME code only proves the schema is internally
//! consistent — it cannot prove the field numbers/wire types actually match
//! a real Meshtastic device, because a bug that flips two field numbers
//! would round-trip against itself perfectly while being wire-incompatible
//! with everything else. That can only be proven against bytes this crate
//! did not produce: a frame captured from a real radio (serial/TCP,
//! stripped of the 4-byte `MeshCodec` header — see `src/codec.rs`), or
//! against the reference Python/JS Meshtastic client.
//!
//! STATUS: unverified. No capture fixture exists yet. Each `#[ignore]`d
//! test below documents the exact assertion a real fixture must satisfy;
//! replace the `todo!()` fixture loader with real captured bytes (e.g.
//! checked in under `proto/fixtures/`, or generated by pairing
//! with a device over serial) and remove `#[ignore]` to turn this from a
//! skeleton into a real gate.

use prost::Message as _;

use crate::proto::{FromRadio, MeshPacket, from_radio};

/// Loads a captured `FromRadio` frame's payload bytes (header already
/// stripped) for a fixture named `name`.
///
/// WHY `todo!()` and not a hardcoded byte array: any placeholder bytes
/// written here without a real capture would just be this crate's own
/// encoder output again, defeating the point of an independent fixture —
/// see the module doc. Wire this to a real captured frame before enabling
/// the tests below.
fn load_fixture(name: &str) -> Vec<u8> {
    todo!("wire captured frame `{name}` from a real radio before enabling wire_compat_tests")
}

/// A `FromRadio` carrying a plain text message, captured from a real
/// device, must decode with the exact field values the capture is known
/// to contain.
///
/// Fill in the expected `from`/`to`/`id`/portnum/payload bytes from
/// whatever fixture `load_fixture("text_message.bin")` ends up loading —
/// the asserts below are placeholders naming WHAT must hold, not values
/// pulled from this schema's own assumptions.
#[test]
#[ignore = "needs a real captured frame; see module doc"]
fn from_radio_text_message_decodes_against_real_capture() {
    let bytes = load_fixture("text_message.bin");

    #[expect(clippy::unwrap_used, reason = "fixture is known-valid once wired")]
    let decoded = FromRadio::decode(bytes.as_slice()).unwrap();

    let Some(from_radio::PayloadVariant::Packet(packet)) = decoded.payload_variant else {
        panic!("expected FromRadio::Packet, got {decoded:?}");
    };

    // WHY placeholders: these must be replaced with the capture's actual
    // values once `load_fixture` is real — a passing assert against a
    // value this schema invented would prove nothing.
    assert_eq!(packet.from, 0, "replace with the capture's real `from`");
    assert_eq!(packet.to, 0, "replace with the capture's real `to`");
}

/// A `MeshPacket` this crate encodes must be byte-identical to what a
/// captured real packet with the SAME field values looks like — i.e. this
/// schema's field numbers and wire types match the real protocol, not
/// just each other.
///
/// This is the strongest form of proof this schema can offer without a
/// live device: it does not just decode a capture, it re-encodes a packet
/// built from that capture's known field VALUES and checks the bytes
/// match, catching a field-number swap that happened to still decode.
#[test]
#[ignore = "needs a real captured frame; see module doc"]
fn mesh_packet_encode_matches_real_capture_bytes() {
    let expected_bytes = load_fixture("mesh_packet_known_values.bin");

    // WHY: construct the SAME logical packet the capture is known to
    // encode, using this schema's types, then compare bytes rather than
    // decoded fields — this is the direction that actually exercises our
    // field numbers instead of prost's own symmetry.
    //
    // TODO(#388): set every field below to the capture's real values
    // (from, to, id, hop_limit, priority, decoded portnum/payload, ...)
    // before removing `#[ignore]`.
    let packet = MeshPacket::default();

    let mut encoded = Vec::new();
    #[expect(clippy::unwrap_used, reason = "encoding a well-formed message cannot fail")]
    packet.encode(&mut encoded).unwrap();

    assert_eq!(
        encoded, expected_bytes,
        "encoded bytes must match the real device's capture exactly, \
         not just round-trip against this crate's own decoder"
    );
}
