syntax = "proto3";
package meshtastic;

// Device-level configuration.
message Config {
  message DeviceConfig {
    enum Role {
      CLIENT = 0;
      CLIENT_MUTE = 1;
      ROUTER = 2;
      ROUTER_CLIENT = 3;
      REPEATER = 4;
      TRACKER = 5;
      SENSOR = 6;
      TAK = 7;
      CLIENT_HIDDEN = 8;
      LOST_AND_FOUND = 9;
    }
    Role role = 1;
    bool serial_enabled = 2;
    bool debug_log_enabled = 3;
    uint32 button_gpio = 4;
    uint32 buzzer_gpio = 5;
    bool rebroadcast_mode = 6;
    uint32 node_info_broadcast_secs = 7;
    bool double_tap_as_button_press = 8;
    bool is_managed = 9;
    bool disable_triple_click = 10;
    string tzdef = 11;
    bool led_heartbeat_disabled = 12;
  }

  message LoRaConfig {
    enum ModemPreset {
      LONG_FAST = 0;
      LONG_SLOW = 1;
      VERY_LONG_SLOW = 2;
      MEDIUM_SLOW = 3;
      MEDIUM_FAST = 4;
      SHORT_SLOW = 5;
      SHORT_FAST = 6;
      LONG_MODERATE = 7;
    }
    bool use_preset = 1;
    ModemPreset modem_preset = 2;
    uint32 bandwidth = 3;
    uint32 spread_factor = 4;
    uint32 coding_rate = 5;
    float frequency_offset = 6;
    uint32 region = 7;
    uint32 hop_limit = 8;
    bool tx_enabled = 9;
    int32 tx_power = 10;
    uint32 channel_num = 11;
    bool override_duty_cycle = 12;
    bool sx126x_rx_boosted_gain = 13;
    float override_frequency = 14;
    bool pa_fan_disabled = 15;
  }

  message NetworkConfig {
    bool wifi_enabled = 1;
    string wifi_ssid = 3;
    string wifi_psk = 4;
    string ntp_server = 5;
    bool eth_enabled = 6;
  }

  oneof payload_variant {
    DeviceConfig device = 1;
    LoRaConfig lora = 6;
    NetworkConfig network = 4;
  }
}
