syntax = "proto3";
package meshtastic;

import "meshtastic/mesh.proto";

// Store-and-forward server statistics.
message StoreAndForward {
  enum RequestResponse {
    UNSET = 0;
    ROUTER_ERROR = 1;
    ROUTER_HEARTBEAT = 2;
    ROUTER_PING = 3;
    ROUTER_PONG = 4;
    ROUTER_BUSY = 5;
    ROUTER_HISTORY = 6;
    ROUTER_STATS = 7;
    ROUTER_TEXT_DIRECT = 8;
    ROUTER_TEXT_BROADCAST = 9;
    CLIENT_ERROR = 100;
    CLIENT_HISTORY = 101;
    CLIENT_STATS = 102;
    CLIENT_PONG = 103;
    CLIENT_ABORT = 104;
  }

  message Statistics {
    uint32 messages_total = 1;
    uint32 messages_saved = 2;
    uint32 messages_max = 3;
    uint32 up_time = 4;
    uint32 requests = 5;
    uint32 requests_history = 6;
    bool is_heartbeat = 7;
    uint32 max_packets = 8;
    uint32 router_history_insert_error = 9;
  }

  message History {
    uint32 history_messages = 1;
    uint32 window = 2;
    uint32 last_request = 3;
  }

  RequestResponse rr = 1;
  oneof variant {
    Statistics stats = 3;
    History history = 4;
    MeshPacket text = 5;
  }
}
